# Generated by Django 5.0.1 on 2024-02-17 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('user', models.CharField(blank=True, max_length=100)),
                ('paymentmethod', models.CharField(blank=True, max_length=200)),
                ('totalprice', models.IntegerField(blank=True, null=True)),
                ('is_paid', models.BooleanField(default=False)),
                ('paid_at', models.DateTimeField(auto_now=True)),
                ('isDelivered', models.BooleanField(default=False)),
                ('title', models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
