# Generated by Django 5.0.1 on 2024-02-19 18:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0003_alter_order_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='title',
        ),
        migrations.AddField(
            model_name='order',
            name='createdat',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='order',
            name='deliveredat',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.CreateModel(
            name='zibal',
            fields=[
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('transId', models.CharField(max_length=100, unique=True)),
                ('lastStatus', models.IntegerField(blank=True, null=True)),
                ('trackIdpay', models.IntegerField(blank=True, null=True)),
                ('trackShaparak', models.CharField(blank=True, max_length=50, null=True)),
                ('amountCreate', models.IntegerField(blank=True, null=True)),
                ('amountPaid', models.IntegerField(blank=True, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('dateUpdate', models.DateTimeField(auto_now=True)),
                ('dateShaparak', models.DateTimeField(blank=True, null=True)),
                ('dateVerify', models.DateTimeField(blank=True, null=True)),
                ('cardNo', models.CharField(blank=True, max_length=30, null=True)),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bank.order')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
