# Generated by Django 5.0.1 on 2024-02-21 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0004_remove_order_title_order_createdat_order_deliveredat_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zibal',
            name='amountCreate',
        ),
        migrations.RemoveField(
            model_name='zibal',
            name='trackIdpay',
        ),
        migrations.RemoveField(
            model_name='zibal',
            name='trackShaparak',
        ),
    ]
