# Generated by Django 5.0.1 on 2024-02-21 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0005_remove_zibal_amountcreate_remove_zibal_trackidpay_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='zibal',
            old_name='createdAt',
            new_name='datepaid',
        ),
        migrations.RemoveField(
            model_name='zibal',
            name='dateShaparak',
        ),
        migrations.RemoveField(
            model_name='zibal',
            name='dateUpdate',
        ),
        migrations.RemoveField(
            model_name='zibal',
            name='dateVerify',
        ),
    ]
