# Generated by Django 5.0.1 on 2024-02-21 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0006_rename_createdat_zibal_datepaid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='zibal',
            name='Condition',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
