# Generated by Django 5.0.1 on 2024-02-21 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0007_zibal_condition'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
